name: Flask App Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./tests/

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Testing
        run: pytest -vv -s --no-header

      - name: Revert commit if test fail
        if: ${{failure()}}
        run: |
          echo "Reverting ${{ github.sha }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git revert --no-edit ${{ github.sha }}
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
