name: Telegram Notify

on:
  workflow_run:
    workflows: [Test Workflow]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      Message: ''
    steps:
      - name: Get commit message
        run: Message=$(git log -1 -pretty=%B)
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Created commit:
            Event: ${{github.event.workflow_run.event}}
            Commit: ${{env.Message}}
            Sha: ${{github.event.workflow_run.head_sha}}
            Status Test: Success
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Status Test: Failed
