name: Telegram Notify

on:
  workflow_run:
    workflows: [Test Workflow]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      Message: ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Commit:
            Actor: ${{github.event.workflow_run.head_commit.author.name}}
            Event: ${{github.event.workflow_run.event}}
            Message: ${{github.event.workflow_run.head_commit.message}}
            Id: ${{github.event.workflow_run.head_commit.id}}
            Status Test: Success
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Status Test: Failed
